# Data sources to query
data_sources:
  - name: search_datastore        # Data source name
    type: opensearch              # Data source type is OpenSearch
    connection:
      host: 127.0.0.1
      port: 9205
      username: !ENV ${OS_USER}   # Username to use for authentication ENV variables
      password: !ENV ${OS_PASS}   # Password to use for authentication ENV variables
  - name: product_db              # Data source name
    type: postgres                # Data source type is Postgres
    connection:
      host: 127.0.0.1
      port: 5421
      username: !ENV ${DB1_USER}  # Username to use for authentication ENV variables
      password: !ENV ${DB1_PASS}  # Password to use for authentication ENV variables
      database: dc_db_1
  - name: search_staging_db       # Data source name
    type: postgres                # Data source type is Postgres
    connection:
      host: 127.0.0.1
      port: 5422
      username: !ENV ${DB2_USER}  # Username to use for authentication ENV variables
      password: !ENV ${DB2_PASS}  # Password to use for authentication ENV variables
      database: dc_db_2

# Metrics to generate
metrics:
  - name: count_us_parts
    metric_type: document_count
    resource: search_datastore.product_data_us
    filters:
      where: '{"match_all" : {}}'
  - name: count_us_parts_valid
    metric_type: row_count
    resource: product_db.products
    filters:
      where: "is_valid is True and country_code = 'US'"
  - name: count_us_parts_not_valid
    metric_type: row_count
    resource: search_staging_db.products
    filters:
      where: "is_valid is False and country_code = 'US'"
  - name: combined_metric_example_percentage
    metric_type: combined
    expression: mul(div(count_us_parts, count_us_parts_valid), 100)
